
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-lanchonete-customer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-lanchonete-customer-deployment
  template:
    metadata:
      labels:
        app: ms-lanchonete-customer-deployment
    spec:
      containers:
      - name: ms-lanchonete-customer
        image: rmontoza/mslanchonetecustomer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: ms-lanchonete-costumer-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: ms-lanchonete-costumer-config
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: ms-lanchonete-costumer-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ms-lanchonete-costumer-config
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-lanchonete-costumer-config
              key: MYSQL_DATABASE
        volumeMounts:
        - name: ms-lanchonete-customer-volume
          mountPath: /app
        ##command: ["/start-web.sh"]  # Substitua isso pelo comando de início apropriado, se necessário
      volumes:
      - name: ms-lanchonete-customer-volume
        emptyDir: {}
