
apiVersion: v1
kind: Service
metadata:
  name: ms-lanchonete-customer-service
spec:
  type: NodePort
  selector:
    app: ms-lanchonete-customer-deployment
  ports:
    - port: 80
      nodePort: 32001 
      targetPort: 3000
